
import random
import turtle
from turtle import *


def maze():
    """Function for the maze itself"""
    #size, speed, starting point
    turtle.pensize(5)
    turtle.speed(0)
    turtle.ht()
    turtle.penup()
    turtle.goto(-300,-300)
    turtle.pendown()
    left(90)

    #main square
    forward(600)
    right(90)
    forward(270)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(300)
    right(90)
    forward(600)
    right(90)
    forward(270)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(300)
    backward(30)

    """Code for all the columns in the maze"""
    #column 1
    right(90)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(150)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    #column 1(end)

    right(90)
    forward(30)
    right(90)
    turtle.pendown()

    #column 2
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(150)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    #column 2(end)

    left(90)
    forward(30)
    left(90)

    #column 3
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(30)
    #column 3(end)

    right(90)
    forward(30)
    right(90)

    #column 4
    forward(60)
    turtle.pendown()
    forward(210)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(30)
    #column 4(end)

    left(90)
    forward(30)
    left(90)

    #column 5
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    #column 5(end)

    right(90)
    forward(30)
    right(90)

    #column 6
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    #column 6(end)

    left(90)
    forward(30)
    left(90)

    #column 7
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(120)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    #column 7(end)

    right(90)
    forward(30)
    right(90)

    #column 8
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(150)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    #column 8(end)

    left(90)
    forward(30)
    left(90)

    #column 9
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(120)
    turtle.pendown()
    forward(150)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(120)
    turtle.penup()
    forward(120)
    #column 9(end)

    right(90)
    forward(30)
    right(90)

    #column 10
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    #column 10(end)

    left(90)
    forward(30)
    left(90)

    #column 11
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(240)
    turtle.pendown()
    forward(30)
    turtle.penup()
    #column 11(end)

    right(90)
    forward(30)
    right(90)

    #column 12
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(120)
    turtle.pendown()
    forward(180)
    turtle.penup()
    forward(30)
    #column 13(end)

    left(90)
    forward(30)
    left(90)

    #column 14
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(150)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(150)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    #column 14(end)

    right(90)
    forward(30)
    right(90)

    #column 15
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(180)
    #column 15(end)

    left(90)
    forward(30)
    left(90)

    #column 16
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    #column 16(end)

    right(90)
    forward(30)
    right(90)

    #column 17
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(150)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(120)
    #column 17(end)

    left(90)
    forward(30)
    left(90)

    #column 18
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(180)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    #column 18(end)

    right(90)
    forward(30)
    right(90)

    #column 19
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(180)
    turtle.penup()
    forward(180)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    #column 19(end)

    left(90)
    forward(30)
    left(90)

    #column 20
    forward(60)
    turtle.pendown()
    forward(180)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    #column 20(end)

    left(90)
    forward(570)
    left(90)
    forward(30)
    left(90)


    """Code for all the rows in the maze"""
    #row 1
    forward(90)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(120)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(90)
    #row 1(end)

    right(90)
    forward(30)
    right(90)

    #row 2
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(150)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    #row 2(end)

    left(90)
    forward(30)
    left(90)

    #row 3
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(210)
    turtle.penup()
    forward(120)
    turtle.pendown()
    forward(30)
    turtle.penup()
    #row 3(end)

    right(90)
    forward(30)
    right(90)

    #row 4
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(150)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    #row 4(end)

    left(90)
    forward(30)
    left(90)

    #row 5
    forward(60)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(90)
    #row 5(end)

    right(90)
    forward(30)
    right(90)

    #row 6
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(150)
    #row 6(end)

    left(90)
    forward(30)
    left(90)

    #row 7
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    #row 7(end)

    right(90)
    forward(30)
    right(90)

    #row 8
    forward(30)
    turtle.pendown()
    forward(150)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    #row 8(end)

    left(90)
    forward(30)
    left(90)

    #row 9
    forward(30)
    turtle.pendown()
    forward(180)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(150)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(90)
    #row 9(end)

    right(90)
    forward(30)
    right(90)

    #row 10
    forward(60)
    turtle.pendown()
    forward(120)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    #row 10(end)

    left(90)
    forward(30)
    left(90)

    #row 11
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(150)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(90)
    turtle.penup()
    #row 11(end)

    right(90)
    forward(30)
    right(90)

    #row 12
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(180)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    #row 12(end)

    left(90)
    forward(30)
    left(90)

    #row 13
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(120)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    #row 13(end)

    right(90)
    forward(30)
    right(90)

    #row 14
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    #row 14(end)

    left(90)
    forward(30)
    left(90)

    #row 15
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(90)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    #row 15(end)

    right(90)
    forward(30)
    right(90)

    #row 16
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(120)
    turtle.penup()
    forward(150)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    #row 16(end)

    left(90)
    forward(30)
    left(90)

    #row 17
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(90)
    #row 17(end)

    right(90)
    forward(30)
    right(90)

    #row 18
    forward(30)
    turtle.pendown()
    forward(120)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(90)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(120)
    turtle.penup()
    forward(30)
    #row 18(end)

    left(90)
    forward(30)
    left(90)

    #row 19
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(60)
    turtle.penup()
    forward(120)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(30)
    turtle.pendown()
    forward(30)
    turtle.penup()
    forward(60)
    turtle.pendown()
    forward(30)
    turtle.penup()
    #row 19(end)

    right(90)
    forward(30)
    right(90)
    forward(285)
    right(90)
    turtle.pendown()
    turtle.st()
    turtle.color("red")

    print ("Welcome to the maze! Choose your path!")
    print ("\nUse W, A, S, D or arrow keys to move around the maze.")
    print ("Press I to write down the movement manually.")
    print
    print ("CAUTION!!!")
    print ("The Walls of the maze are NOT an obstacle.")
    print ("Please avoid going through them at any time")
    print ("for the purpose of your own entertainment in this program.")

maze()

def win():
    if turtle.pos() == (-15, 300):
        print
        print ("Congratulations! You won!!!")
        print ("You can have a candy.")
        print

def up():
    setheading(90)
    forward(15)
def down():
    setheading(270)
    forward(15)
def right():
    setheading(0)
    forward(15)
def left():
    setheading(180)
    forward(15)

def strToList(S):
    """Make a list from a string"""
    if len(S) == 0: return []
    return [S[0]] + strToList(S[1:])

def movement():    
    L = ["Where do you want to go next?", "Where will be your next turn?",
         "Left, Right or Forward?", "What is your destination?",
         "Where are you heading to?"]
    print (random.choice(L))
    button = raw_input()
    commands = strToList(button)
    move(commands)
    turtle.mainloop()

def move(commands):
    if commands == []:
        return movement()
    elif commands[0] == "w":
        setheading(90)
        forward(15)
        print ("Going forward 15")
    elif commands[0] == "s":
        setheading(270)
        forward(15)
        print ("Going backward 15")
    elif commands[0] == "a":
        setheading(180)
        forward(15)
        print ("Turning left then going forward 15")
    elif commands[0] == "d":
        setheading(0)
        forward(15)
        print ("Turning right then going forward 15")
    else:
        print ("Press W, S, A, D")
    move(commands[1:])
    turtle.mainloop()

onkey(up, "w")
#onkey(up, "up")
onkey(down, "s")
#onkey(down, "down")
onkey(right, "d")
#onkey(right, "right")
onkey(left, "a")
#onkey(left, "left")
onkey(movement, "i")
listen()
mainloop()
